CREATE TABLE `ipc_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dev_type` tinyint(4) DEFAULT NULL COMMENT '四分类垃圾箱有屏幕',
  `imei` varchar(56) DEFAULT NULL COMMENT 'IMEI号为通讯模块固定串号',
  `app_version` varchar(56) DEFAULT NULL COMMENT '例V3.1.1',
  `motor_control_s_v` varchar(56) DEFAULT NULL COMMENT '电机控制板软件版本',
  `motor_control_h_v` varchar(56) DEFAULT NULL COMMENT '电机控制板硬件版本',
  `range_sensor_s_v` varchar(56) DEFAULT NULL COMMENT '距离传感器软件版本',
  `range_sensor_h_v` varchar(56) DEFAULT NULL COMMENT '距离传感器硬件版本',
  `motor_contr_n_a` smallint(6) DEFAULT NULL COMMENT '电机控制板参数:正常工作电流下限',
  `motor_contr_b_a` smallint(6) DEFAULT NULL COMMENT '电机控制板参数: 堵转电流下限',
  `garbage_p_height` smallint(6) DEFAULT NULL COMMENT '垃圾箱物理高度',
  `garbage_r_height` smallint(6) DEFAULT NULL COMMENT '垃圾箱实际高度',
  `fill_line` smallint(6) DEFAULT NULL COMMENT '溢满线',
  `clear_line` smallint(6) DEFAULT NULL COMMENT '清除线',
  `temperature_threshold` smallint(6) DEFAULT NULL COMMENT '温度阈值',
  `angle_threshold` smallint(6) DEFAULT NULL COMMENT '角度阈值',
  `dev_id` varchar(56) DEFAULT NULL COMMENT '设备编号',
  `door_o_c_time` smallint(6) DEFAULT NULL COMMENT '开关门最大时间',
  `low_power_voltage_alarm_line` smallint(6) DEFAULT NULL COMMENT '动力电压过低报警线',
  `power_voltage_normal_alarm_line` smallint(6) DEFAULT NULL COMMENT '动力电压正常报警线',
  `high_power_voltage_alarm_line` smallint(6) DEFAULT NULL COMMENT '动力电压过高报警线',
  PRIMARY KEY (`id`),
  KEY `idx_dev_id` (`dev_id`)
) ENGINE=InnoDB AUTO_INCREMENT=403 DEFAULT CHARSET=utf8 COMMENT='工控机注册表'