CREATE TABLE `mask_terminal_infomation_copy` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dev_id` varchar(255) DEFAULT NULL COMMENT 'SN号',
  `imei` varchar(255) DEFAULT NULL COMMENT 'imei号',
  `dev_name` varchar(255) DEFAULT NULL COMMENT '设备名称',
  `combination` varchar(255) DEFAULT NULL COMMENT '组织机构',
  `dev_type` varchar(255) DEFAULT NULL COMMENT '设备类型',
  `device_id` varchar(255) DEFAULT NULL COMMENT '设备ID',
  `maintenance_man` varchar(255) DEFAULT NULL COMMENT '维护人',
  `location` varchar(255) DEFAULT NULL COMMENT '位置',
  `latitude` double DEFAULT NULL COMMENT '纬度',
  `longitude` double DEFAULT NULL COMMENT '经度',
  `product_model` varchar(255) DEFAULT NULL COMMENT '设备型号',
  `connect_type` varchar(255) DEFAULT NULL COMMENT '连接方式',
  `version` varchar(255) DEFAULT NULL COMMENT '版本号',
  `dev_sim_num` varchar(255) DEFAULT NULL COMMENT '卡号',
  `rubbish_height` varchar(255) DEFAULT NULL COMMENT '垃圾桶高度',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `combination_id` int(11) DEFAULT NULL COMMENT '组织机构ID',
  `group_id` int(11) DEFAULT '0' COMMENT '分组ID',
  `delete_flag` int(11) DEFAULT '0' COMMENT '软删除的标识 0未删除 1删除',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `group_type` varchar(12) DEFAULT 'C' COMMENT 'A一拖二 B 一拖一 C 其他',
  `garbage_id` int(11) DEFAULT '0' COMMENT '垃圾桶id，贴在桶上',
  `full` int(11) DEFAULT '0',
  `haswork` int(11) DEFAULT '0',
  `mArea` varchar(256) DEFAULT '',
  `area` int(11) DEFAULT '81',
  `user_id` varchar(256) DEFAULT 'none',
  `push` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8