CREATE TABLE `report_data` (
  `notify_type` varchar(255) DEFAULT NULL,
  `device_id` varchar(255) DEFAULT NULL,
  `gateway_id` varchar(255) DEFAULT NULL,
  `request_id` varchar(255) DEFAULT NULL,
  `service_id` varchar(255) DEFAULT NULL,
  `service_type` varchar(255) DEFAULT NULL,
  `msg_id` varchar(255) DEFAULT NULL,
  `msg_serial_num` varchar(255) DEFAULT NULL,
  `property` varchar(255) DEFAULT NULL,
  `dev_id` varchar(255) DEFAULT NULL COMMENT '终端ID号',
  `report_type` varchar(255) DEFAULT NULL COMMENT '上报类型',
  `dev_status` varchar(255) DEFAULT NULL COMMENT '设备状态',
  `connect_type` varchar(255) DEFAULT NULL COMMENT '接入方式',
  `bat_v` varchar(255) DEFAULT NULL COMMENT '电池电压',
  `signal_q` varchar(255) DEFAULT NULL COMMENT '信号质量',
  `pkg_serial_num` varchar(255) DEFAULT NULL COMMENT '数据包数',
  `rubbish_l` varchar(255) DEFAULT NULL COMMENT '左侧垃圾量高度',
  `rubbish_r` varchar(255) DEFAULT NULL COMMENT '右侧垃圾量高度',
  `tmp` varchar(255) DEFAULT NULL COMMENT '温度',
  `angle` varchar(255) DEFAULT NULL COMMENT '倾角',
  `x_axis` varchar(255) DEFAULT NULL COMMENT '静态X轴',
  `y_axis` varchar(255) DEFAULT NULL COMMENT '静态y轴',
  `z_axis` varchar(255) DEFAULT NULL COMMENT '静态Z轴',
  `year` varchar(255) DEFAULT NULL,
  `month` varchar(255) DEFAULT NULL,
  `day` varchar(255) DEFAULT NULL,
  `hour` varchar(255) DEFAULT NULL,
  `min` varchar(255) DEFAULT NULL,
  `sec` varchar(255) DEFAULT NULL,
  `msg_check_sum` varchar(255) DEFAULT NULL COMMENT '检验和',
  `event_time` varchar(255) DEFAULT NULL COMMENT '接收数据时间',
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `dev_sim_num` varchar(255) DEFAULT NULL COMMENT '网络地址',
  `current_z_time` varchar(255) DEFAULT NULL,
  `dev_model` varchar(255) DEFAULT NULL,
  `soft_ver` varchar(255) DEFAULT NULL,
  `dev_imei` varchar(255) DEFAULT NULL,
  `dev_real_hight` varchar(255) DEFAULT NULL,
  `dev_type` varchar(255) DEFAULT NULL,
  `reply_flg` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `device_id` (`device_id`) USING HASH,
  KEY `dev_id` (`dev_id`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=787145 DEFAULT CHARSET=utf8