CREATE TABLE `terminal_select_answer` (
  `notify_type` varchar(255) DEFAULT NULL,
  `service_id` varchar(255) DEFAULT NULL,
  `device_id` varchar(255) DEFAULT NULL,
  `gateway_id` varchar(255) DEFAULT NULL,
  `service_type` varchar(255) DEFAULT NULL,
  `event_time` varchar(255) DEFAULT NULL,
  `msg_id` varchar(255) DEFAULT NULL,
  `msg_serial_num` varchar(255) DEFAULT NULL,
  `property` varchar(255) DEFAULT NULL,
  `reply_serial_num` varchar(255) DEFAULT NULL,
  `reply_id` varchar(255) DEFAULT NULL,
  `reply_flg` varchar(255) DEFAULT NULL,
  `dustbin_hight` varchar(255) DEFAULT NULL COMMENT '垃圾箱物理高度',
  `dustbin_real_hight` varchar(255) DEFAULT NULL COMMENT '垃圾箱实际高度',
  `full` varchar(255) DEFAULT NULL COMMENT '溢满线',
  `clear` varchar(255) DEFAULT NULL COMMENT '清除线',
  `tmp` varchar(255) DEFAULT NULL COMMENT '温度阙值',
  `angle` varchar(255) DEFAULT NULL COMMENT '角度阙值',
  `t_trigger` varchar(255) DEFAULT NULL COMMENT '触发方式',
  `sample_period` varchar(255) DEFAULT NULL COMMENT '采样周期',
  `heartbeat_period` varchar(255) DEFAULT NULL COMMENT '心跳周期',
  `open_timeout` varchar(255) DEFAULT NULL COMMENT '开盖超时',
  `bat_v` varchar(255) DEFAULT NULL COMMENT '截止电压',
  `msg_check_sum` varchar(255) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1778 DEFAULT CHARSET=utf8