CREATE TABLE `well_lid_infomation` (
  `dev_id` varchar(255) DEFAULT NULL COMMENT 'SN号',
  `imei` varchar(255) DEFAULT NULL COMMENT 'imei号',
  `dev_name` varchar(255) DEFAULT NULL COMMENT '设备名称',
  `combination` varchar(255) DEFAULT NULL COMMENT '组织机构',
  `dev_type` varchar(255) DEFAULT NULL COMMENT '设备类型',
  `device_id` varchar(255) DEFAULT NULL COMMENT '设备ID',
  `maintenance_man` varchar(255) DEFAULT NULL COMMENT '维护人',
  `latitude` varchar(255) DEFAULT NULL COMMENT '纬度',
  `longitude` varchar(255) DEFAULT NULL COMMENT '经度',
  `product_model` varchar(255) DEFAULT NULL COMMENT '设备型号',
  `connect_type` varchar(255) DEFAULT NULL COMMENT '连接方式',
  `version` varchar(255) DEFAULT NULL COMMENT '版本号',
  `dev_sim_num` varchar(255) DEFAULT NULL COMMENT '卡号',
  `well_lid_height` varchar(255) DEFAULT NULL COMMENT '井盖高度',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `combination_id` int(11) DEFAULT NULL COMMENT '组织机构ID',
  `group_id` int(11) DEFAULT '0' COMMENT '分组ID',
  `delete_flag` int(11) DEFAULT '0' COMMENT '软删除的标识 0未删除 1删除',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `group_type` varchar(12) DEFAULT 'C' COMMENT 'A一拖二 B 一拖一 C 其他',
  `garbage_id` int(11) DEFAULT '0' COMMENT '垃圾桶id',
  PRIMARY KEY (`id`),
  KEY `dev_id` (`dev_id`),
  KEY `device_id` (`device_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8