mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath*:mapper/*.xml
    type-handlers-package: com.lixin.typehandler

server:
    port: 6688
    servlet:
        context-path: /stock

spring:
    datasource:
        master:
            driverClassName: com.mysql.jdbc.Driver
            password: lixin
            type: com.zaxxer.hikari.HikariDataSource
            url: jdbc:mysql://127.0.0.1:3306/lixin?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: lixin
        slave:
            driverClassName: com.mysql.jdbc.Driver
            password: lixin
            type: com.zaxxer.hikari.HikariDataSource
            url: jdbc:mysql://127.0.0.1:3306/lixin?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: lixin
