server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.0.211:3306/lixintest?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: lixin
    password: 188282lll
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations:
    - classpath*:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

