CREATE TABLE `mask_dev_reg_answer` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `devId` varchar(128) DEFAULT NULL,
  `deviceId` varchar(128) DEFAULT NULL,
  `serviceType` varchar(128) DEFAULT NULL,
  `msgSerialNum` varchar(128) DEFAULT NULL,
  `property` varchar(128) DEFAULT NULL,
  `reSendNum` varchar(128) DEFAULT NULL,
  `replySerialNum` varchar(128) DEFAULT NULL,
  `replyID` varchar(128) DEFAULT NULL,
  `replyFlg` varchar(128) DEFAULT NULL,
  `devType` varchar(128) DEFAULT NULL,
  `connectType` varchar(128) DEFAULT NULL,
  `devRealHight` varchar(128) DEFAULT NULL,
  `devImsi` varchar(128) DEFAULT NULL,
  `devImei` varchar(128) DEFAULT NULL,
  `devModel` varchar(128) DEFAULT NULL,
  `regYear` varchar(128) DEFAULT NULL,
  `regMonth` varchar(128) DEFAULT NULL,
  `regDay` varchar(128) DEFAULT NULL,
  `regHour` varchar(128) DEFAULT NULL,
  `regMin` varchar(128) DEFAULT NULL,
  `regSec` varchar(128) DEFAULT NULL,
  `activeYear` varchar(128) DEFAULT NULL,
  `activeMonth` varchar(128) DEFAULT NULL,
  `activeDay` varchar(128) DEFAULT NULL,
  `activeHour` varchar(128) DEFAULT NULL,
  `activeMin` varchar(128) DEFAULT NULL,
  `activeSec` varchar(128) DEFAULT NULL,
  `softVer` varchar(128) DEFAULT NULL,
  `doorSoftVer` varchar(128) DEFAULT NULL,
  `msgCheckSum` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `dev_id_i` (`devId`),
  KEY `device_id_i` (`deviceId`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8