CREATE TABLE `mask_regular_data_up` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `dev_id` varchar(128) DEFAULT NULL,
  `device_id` varchar(128) DEFAULT NULL,
  `service_type` varchar(128) DEFAULT NULL,
  `msg_serial_num` varchar(128) DEFAULT NULL,
  `property` varchar(128) DEFAULT NULL,
  `re_send_num` varchar(128) DEFAULT NULL,
  `report_type` varchar(128) DEFAULT NULL,
  `dev_status` varchar(128) DEFAULT NULL,
  `connect_type` varchar(128) DEFAULT NULL,
  `bat_v` varchar(128) DEFAULT NULL,
  `CSQ` varchar(128) DEFAULT NULL,
  `signal_power` varchar(128) DEFAULT NULL,
  `total_power` varchar(128) DEFAULT NULL,
  `tx_power` varchar(128) DEFAULT NULL,
  `SNR` varchar(128) DEFAULT NULL,
  `RSRQ` varchar(128) DEFAULT NULL,
  `RSRP` varchar(128) DEFAULT NULL,
  `cell_id` varchar(128) DEFAULT NULL,
  `PCI` varchar(128) DEFAULT NULL,
  `ECL` varchar(128) DEFAULT NULL,
  `motor_power_v` varchar(128) DEFAULT NULL,
  `digital_v` varchar(128) DEFAULT NULL,
  `pkg_serial_num` varchar(128) DEFAULT NULL,
  `rubbish_l` varchar(128) DEFAULT NULL,
  `rubbish_r` varchar(128) DEFAULT NULL,
  `temp` varchar(128) DEFAULT NULL,
  `angle` varchar(128) DEFAULT NULL,
  `x_axis` varchar(128) DEFAULT NULL,
  `y_axis` varchar(128) DEFAULT NULL,
  `z_axis` varchar(128) DEFAULT NULL,
  `year` varchar(128) DEFAULT NULL,
  `month` varchar(128) DEFAULT NULL,
  `day` varchar(128) DEFAULT NULL,
  `hour` varchar(128) DEFAULT NULL,
  `min` varchar(128) DEFAULT NULL,
  `sec` varchar(128) DEFAULT NULL,
  `door_err_status` varchar(128) DEFAULT NULL,
  `door_curr_status` varchar(128) DEFAULT NULL,
  `door_i_max` varchar(128) DEFAULT NULL,
  `door_i_min` varchar(128) DEFAULT NULL,
  `door_v_max` varchar(128) DEFAULT NULL,
  `door_v_min` varchar(128) DEFAULT NULL,
  `delivery_times` varchar(56) DEFAULT NULL COMMENT '0',
  `msg_check_sum` varchar(128) DEFAULT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `dev_id_i` (`dev_id`),
  KEY `device_id_i` (`device_id`)
) ENGINE=InnoDB AUTO_INCREMENT=35741 DEFAULT CHARSET=utf8