CREATE TABLE `terminal_infomation_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dev_id` varchar(255) DEFAULT NULL COMMENT 'SN号',
  `imei` varchar(255) DEFAULT NULL COMMENT 'imei号',
  `dev_name` varchar(255) DEFAULT NULL COMMENT '设备名称',
  `combination` varchar(255) DEFAULT NULL COMMENT '组织机构',
  `dev_type` varchar(255) DEFAULT NULL COMMENT '设备类型',
  `device_id` varchar(255) DEFAULT NULL COMMENT '设备ID',
  `maintenance_man` varchar(255) DEFAULT NULL COMMENT '维护人',
  `location` varchar(255) DEFAULT NULL COMMENT '位置',
  `latitude` varchar(255) DEFAULT NULL COMMENT '纬度',
  `longitude` varchar(255) DEFAULT NULL COMMENT '经度',
  `product_model` varchar(255) DEFAULT NULL COMMENT '设备型号',
  `connect_type` varchar(255) DEFAULT NULL COMMENT '连接方式',
  `version` varchar(255) DEFAULT NULL COMMENT '版本号',
  `dev_sim_num` varchar(255) DEFAULT NULL COMMENT '卡号',
  `rubbish_height` varchar(255) DEFAULT NULL COMMENT '垃圾桶高度',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `combination_id` int(11) DEFAULT NULL COMMENT '组织机构ID',
  `group_id` int(11) DEFAULT '0' COMMENT '分组ID',
  `delete_flag` int(11) DEFAULT '0' COMMENT '软删除的标识 0未删除 1删除',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `group_type` varchar(12) DEFAULT 'C' COMMENT 'A一拖二 B 一拖一 C 其他',
  `garbage_id` int(11) DEFAULT '0' COMMENT '垃圾桶id，贴在桶上',
  `lon84` varchar(128) DEFAULT NULL comment '84坐标',
  `lat84` varchar(128) DEFAULT NULL comment '84坐标',
  `type` tinyint(4) DEFAULT '0' COMMENT '0 可回收 不可回收',
  `full` int(11) DEFAULT '0' COMMENT '溢满标识',
  `area` int(11) DEFAULT NULL COMMENT '区域编号',
  `mArea` varchar(256) DEFAULT NULL COMMENT '区域名字',
  `haswork` int(11) DEFAULT '0' COMMENT '0 代表没有车辆去清收1 代表有车辆去请收',
  PRIMARY KEY (`id`),
  UNIQUE KEY `dev_id_i` (`dev_id`)
) ENGINE=InnoDB AUTO_INCREMENT=216 DEFAULT CHARSET=utf8