CREATE TABLE `well_lid_report_data` (
  `notify_type` varchar(255) DEFAULT NULL,
  `device_id` varchar(255) DEFAULT NULL,
  `gateway_id` varchar(255) DEFAULT NULL,
  `service_id` varchar(255) DEFAULT NULL,
  `service_type` varchar(255) DEFAULT NULL,
  `msg_serial_num` varchar(255) DEFAULT NULL,
  `property` varchar(255) DEFAULT NULL COMMENT '指令体属性',
  `dev_id` varchar(255) DEFAULT NULL COMMENT '终端ID号',
  `report_type` varchar(255) DEFAULT NULL COMMENT '上报类型',
  `dev_status` varchar(255) DEFAULT NULL COMMENT '设备状态',
  `connect_type` varchar(255) DEFAULT NULL COMMENT '接入方式',
  `bat_v` varchar(255) DEFAULT NULL COMMENT '电池电压',
  `signal_q` varchar(255) DEFAULT NULL COMMENT '信号质量',
  `pkg_serial_num` varchar(255) DEFAULT NULL COMMENT '数据包数',
  `tmp` varchar(255) DEFAULT NULL COMMENT '温度',
  `angle` varchar(255) DEFAULT NULL COMMENT '倾角',
  `gas_one` int(11) DEFAULT NULL COMMENT '毒气 1 含量',
  `gas_two` int(11) DEFAULT NULL COMMENT '毒气 2 含量',
  `flood` int(11) DEFAULT NULL COMMENT '水浸 0：未被水浸没； 1：被水浸没',
  `liquid_level` int(11) DEFAULT NULL COMMENT '探头到液面的高度单位',
  `vibration_num` int(11) DEFAULT NULL COMMENT '震动次数',
  `year` varchar(255) DEFAULT NULL,
  `month` varchar(255) DEFAULT NULL,
  `day` varchar(255) DEFAULT NULL,
  `hour` varchar(255) DEFAULT NULL,
  `min` varchar(255) DEFAULT NULL,
  `sec` varchar(255) DEFAULT NULL,
  `msg_check_sum` varchar(255) DEFAULT NULL COMMENT '检验和',
  `event_time` varchar(255) DEFAULT NULL COMMENT '接收数据时间',
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `dev_sim_num` varchar(255) DEFAULT NULL COMMENT '网络地址',
  `current_z_time` varchar(255) DEFAULT NULL,
  `dev_model` varchar(255) DEFAULT NULL,
  `soft_ver` varchar(255) DEFAULT NULL,
  `dev_imei` varchar(255) DEFAULT NULL,
  `dev_type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7368 DEFAULT CHARSET=utf8