CREATE TABLE `well_lid_infomation` (
  `dev_id` tinytext,
  `imei` tinytext,
  `dev_name` tinytext,
  `combination` tinytext,
  `dev_type` tinytext,
  `device_id` tinytext,
  `maintenance_man` tinytext,
  `latitude` tinytext,
  `longitude` tinytext,
  `product_model` tinytext,
  `connect_type` tinytext,
  `version` tinytext,
  `dev_sim_num` tinytext,
  `well_lid_height` tinytext,
  `remark` tinytext,
  `id` int(11) DEFAULT NULL,
  `combination_id` int(11) DEFAULT NULL,
  `group_id` int(11) DEFAULT NULL,
  `delete_flag` int(11) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `group_type` tinytext,
  `garbage_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8